title: Foreshadow
author: bourbonbaron2
email: bourbonbaron@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Training for Winter.

# social links
twitter_username: bourbonbaron2 # DO NOT include the @ character, or else the build will fail!
github_username:  bourbonbaron2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
